// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apunts: [
    'intro',
    {
      type: 'category',
      label: 'BA1 — Fonaments i infraestructura d\'IA',
      link: {type: 'doc', id: 'ba1-fonaments-ia/index'},
      items: [{type: 'autogenerated', dirName: 'ba1-fonaments-ia'}],
    },
    {
      type: 'category',
      label: 'BA2 — Comunicació professional amb IA',
      link: {type: 'doc', id: 'ba2-comunicacio-professional/index'},
      items: [{type: 'autogenerated', dirName: 'ba2-comunicacio-professional'}],
    },
    {
      type: 'category',
      label: 'BA3 — Contingut, fonts i comunicació visual',
      link: {type: 'doc', id: 'ba3-contingut-fonts-visual/index'},
      items: [{type: 'autogenerated', dirName: 'ba3-contingut-fonts-visual'}],
    },
    {
      type: 'category',
      label: 'BA4 — Dades i professionalització',
      link: {type: 'doc', id: 'ba4-dades-professionalitzacio/index'},
      items: [{type: 'autogenerated', dirName: 'ba4-dades-professionalitzacio'}],
    },
    {
      type: 'category',
      label: 'Recursos',
      link: {type: 'doc', id: 'recursos/index'},
      items: [{type: 'autogenerated', dirName: 'recursos'}],
    },
  ],
};

export default sidebars;
